[package]
name = "ucp_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
pelican_ui = {path = "../pelican_ui"} #"1.0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
rust_on_rails = {path="../rust_on_rails"}
serde = "1.0.219"
tokio = { version = "1.45.0", features = ["time"] }


#[lib]
#name="main"
#crate-type=["staticlib", "cdylib", "rlib"]
#crate-type=["cdylib"]
